[package]
name = "shrtn"
version = "0.2.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "3", default-features = false }
bb8-postgres = "0.5"
env_logger = "0.8"
serde = { version = "1.0", features = ["derive"] }
rand =  "0.7"
dashmap = "4.0.0-rc.6"

[profile.release]
lto = "thin"
