[package]
name = "shrtn"
version = "0.1.0"
authors = ["Jens Reidel <jens@troet.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "1.0"
bytes = "0.4.12"
askama = "0.8"
futures = "0.1"
serde = "1.0"
rand =  "0.7"
lazy_static = "1.4"
serde_derive = "1.0"

[dependencies.diesel]
features = ["postgres", "r2d2"]
version = "1.4"
